#Spring
spring:
  application:
  name: myapp
  profiles:
  active: "dev"

---

spring:
  profiles: dev
server:
  ip: 127.0.0.1
  port: ${SERVER_PORT:8081}

---

spring:
  profiles: prod
server:
  ip: 127.0.0.1
  port: ${SERVER_PORT:8082}

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false